pub(super) const SKILL_FILES: &[(&str, &str)] = &[
    (
        "SKILL.md",
        include_str!("../../../../skills/mosaico/SKILL.md"),
    ),
    (
        "agents/openai.yaml",
        include_str!("../../../../skills/mosaico/agents/openai.yaml"),
    ),
    (
        "references/channel-creation.md",
        include_str!("../../../../skills/mosaico/references/channel-creation.md"),
    ),
    (
        "references/coordination-guide.md",
        include_str!("../../../../skills/mosaico/references/coordination-guide.md"),
    ),
    (
        "references/cross-workspace.md",
        include_str!("../../../../skills/mosaico/references/cross-workspace.md"),
    ),
    (
        "references/headless-mode.md",
        include_str!("../../../../skills/mosaico/references/headless-mode.md"),
    ),
    (
        "references/identity-and-capabilities.md",
        include_str!("../../../../skills/mosaico/references/identity-and-capabilities.md"),
    ),
    (
        "references/mcp-chatbot-setup.md",
        include_str!("../../../../skills/mosaico/references/mcp-chatbot-setup.md"),
    ),
    (
        "references/public-work-status.md",
        include_str!("../../../../skills/mosaico/references/public-work-status.md"),
    ),
];
